version: '3'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_ADMIN_USER=$MYSQL_ADMIN_USER
      - MYSQL_ADMIN_PASSWORD=$MYSQL_ADMIN_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_USER_PASSWORD=$MYSQL_USER_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - my-network

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - cert-etc:/etc/ssl
    networks:
      - my-network

  cert:
    depends_on:
      - nginx
    build: requirements/tools/cert
    container_name: cert
    volumes:
      - cert-etc:/etc/ssl
      - wordpress:/var/www/html
    networks:
      - my-network

volumes:
  cert-etc:
  wordpress:
  dbdata:

networks:
    my-network:
