CREATE DATABASE IF NOT EXISTS wordpress;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES on *.* TO getenv('MYSQL_ADMIN_USER')@'%' IDENTIFIED BY getenv('MYSQL_ADMIN_PASSWORD') WITH GRANT OPTION;
CREATE USER getenv('MYSQL_USER')@'%' IDENTIFIED BY getenv('MYSQL_USER_PASSWORD');
FLUSH PRIVILEGES;
